# site settings
url: "http://letsta.lk"
baseurl: ""
# "http://abrelatam.org"
twitter_username: go_letstalk
analytics: 'UA-61272908-1'

# build settings
markdown: kramdown

people:
  app_id: 726557177416279

companies:
  app_id: 726557177416279

en:
  title: Reinventing the customer service.
  site_name: Let's Talk 
  description: "Chat with your customers. Let's Talk is the best way to stay in touch with your customers. Lower your costs and improve your service."
es:
  title: Reinventando la atención al cliente.
  site_name: Let's Talk 
  description: "Conversa con tus clientes. Let's Talk es la mejor herramienta para estar en contacto con tus clientes. Menos costos y mejor servicio."
