# site settings
title: Abrelatam
# email: info@ciudadanointeligente.org
description: Abrelatam 2015
baseurl: "http://ciudadanointeligente.github.io/abrelatam/"
# "http://abrelatam.org"
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
# analytics: 'UA-41822715-1'

# build settings
markdown: kramdown
