# site settings
title: Abrelatam 2015
# email: info@ciudadanointeligente.org
description: "Un encuentro abierto, por una región abierta"
baseurl: "http://2015.abrelatam.org/"
# "http://abrelatam.org"
twitter_username: abrelatam
github_username:  ciudadanointeligente
analytics: 'UA-60181338-1'

# build settings
markdown: kramdown
