# site settings
title: Let's Talk 
# email: info@ciudadanointeligente.org
description: "pure an simple communication"
url: "http://lets-talk.github.io"
baseurl: "/homepage"
# "http://abrelatam.org"
twitter_username: ciudadanoi
github_username:  ciudadanointeligente
# analytics: 'UA-41822715-1'

# build settings
markdown: kramdown
