# site settings
title: Let's Talk 
# email: info@ciudadanointeligente.org
description: "Chatea gratis con empresas y servicios."
url: "http://letsta.lk"
baseurl: ""
# "http://abrelatam.org"
twitter_username: go_letstalk
analytics: 'UA-61272908-1'

# build settings
markdown: kramdown
